### ISSUE TITLE
Improve robustness of linkToTitle

### ISSUE THREAD

**Issue by zhutianchi-mcarlo** [mcdexio/gov-fe#2]
The linkToTitle depends on the link format. But if there is a slight operation error, all proposals will not be listed.

```
export const linkToTitle = (link) =>
  link
    .split('/')[4]    // Note that segment 4 may be missing
    .split('-')
...
```

### How to reproduce

1. Press "+"
2. Set the URL to "https://google.com"
3. Create this proposal

Expected: Tolerate errors when listing, such as displaying "Unkown title"
Actual: The whole list is empty

**Comment by sulliwane** [comment]
Fixed in https://github.com/mcdexio/gov-fe/commit/ffcd1ab26e362a40d5eb0df6a672e49acfca4778.

I'll let you know when demo page is updated so you can confirm the bug is fixed.

**Comment by mcarlo-mzc** [comment]
After testing, in the latest code version, this problem has been fixed.
