### ISSUE TITLE
Crash when pressing "My Account" 

### ISSUE THREAD

**Issue by zhutianchi-mcarlo** [mcdexio/gov-fe#3]
White screen after I press "My Account".

The last request
```
query getProposal($id: ID!, $addressUniswap: String!) {...}
variables: {id: "0x3c83b7982bd4ce2f308a9bd59721fb820292c7a4", addressUniswap: "0x9e99f7d76563a9b087f159d2599478826d9f729d" }
```

Returns
```
{"data":{"account":null, ...}}
```

Error at
```
TypeError: Cannot read property 'balance' of undefined
(anonymous function)
src/Voter.js:208
```

### How to reproduce

1. Press "Connect Wallet" and connect to the MetaMask
2. After showing "My Account" at the right top corner, press "My Account"

Actual: White screen

**Comment by sulliwane** [comment]
Fixed in https://github.com/mcdexio/gov-fe/commit/49c19121e9df895490f1cf79be44d943f6d3414d.

I'll let you know when demo page is updated so you can confirm the bug is fixed.

**Comment by mcarlo-mzc** [comment]
After testing, this problem has been fixed on the new latest code version.

**Comment by mcarlo-mzc** [comment]
I tried multiple accounts, only one account had this problem again, in our deployment environment..

address: 0x5439c5E74c3372cFC6f3363A8A579e269A774769

The last request
```
{
    "operationName": "getProposal",
    "variables": {
        "id": "0x5439c5e74c3372cfc6f3363a8a579e269a774769",
        "addressUniswap": "0x92d21865f16e00a54f7face0de5157c31b61d526"
    },
    "query": "query getProposal($id: ID!, $addressUniswap: String!) { uniMCBAccount: account(id: $addressUniswap) { id balancesLatest { id balance totalSupply block __typename } __typename } account(id: $id) { id balances: balancesLatest { id balance totalSupply contract { id __typename } __typename } votes { id timestamp proposal { id link endBlock beginBlock __typename } content __typename } __typename }}"
}
```

Returns
```
{"data":{"account":{"__typename":"Account","balances":[], ......}
```

Error at
```
TypeError: Cannot read property 'balance' of undefined
(anonymous function)
src/Voter.js:210
```

**Comment by zhutianchi-mcarlo** [comment]
I reproduced this bug again.

### How to reproduce

1. User A has some MCBs
2. User A vote "For" or "Against" once
3. User A transfer all MCBs to User B
4. User A press "My Account" button

Actual: White screen.

**Comment by sulliwane** [comment]
Thanks @zhutianchi-mcarlo :+1:  I'm fixing it

**Comment by sulliwane** [comment]
should be fixed in https://github.com/mcdexio/gov-fe/commit/8fffd3eda890ceed6a8a7d323c552599f17fc301
