### ISSUE TITLE
finish voting page need auto refresh

### ISSUE THREAD

**Issue by realmeh** [mcdexio/gov-fe#4]
after voting， user need to refresh the page manually to see result, it is suggested to change to auto refresh

**Comment by mcarlo-mzc** [comment]
I reconfirmed this question. After the wallet is successfully linked, the page will automatically refresh the current voting information.

**Comment by sulliwane** [comment]
Hey @mcarlo-mzc, do you confirm the bug _exists_ or _does not exist_? Thanks :)

**Comment by mcarlo-mzc** [comment]
@sulliwane  I have confirmed many times, it does not exist.

**Comment by sulliwane** [comment]
Thanks, @mcarlo-mzc. Closing then
