### ISSUE TITLE
wallet connect status 

### ISSUE THREAD

**Issue by realmeh** [mcdexio/gov-fe#5]
When  user refreshes the page or vote, the wallet needs to be reconnected, should be stay login

**Comment by sulliwane** [comment]
Fixed in https://github.com/mcdexio/gov-fe/commit/27c2fc6233a6483d006dc3b9b7bea8dbc9fd5732

I'll let you know when demo page is updated so you can confirm the bug is fixed.

**Comment by mcarlo-mzc** [comment]
After testing, in the latest code version, this problem has been fixed.
