### ISSUE TITLE
network error remind

### ISSUE THREAD

**Issue by realmeh** [mcdexio/gov-fe#6]
when user in  wrong network, click connect and nothing response to user, need remind user switch network

**Comment by sulliwane** [comment]
Fixed in https://github.com/mcdexio/gov-fe/commit/a93135d76ed6b5f9be399756b76a2bdb8d72a581

I'll let you know when demo page is updated so you can confirm the bug is fixed.

**Comment by mcarlo-mzc** [comment]
After testing, in the latest code version, this problem has been fixed
