### ISSUE TITLE
Button disabled after voting

### ISSUE THREAD

**Issue by mcarlo-mzc** [mcdexio/gov-fe#7]
when a user has voted for a support direction on a solution, but the button in the support direction can still be clicked, it is recommended to disable the button for which the user has already voted.

**Comment by sulliwane** [comment]
Fixed in last demo version

**Comment by mcarlo-mzc** [comment]
I hope that users can change their minds to vote against after they have voted in support, and support users can change their minds after they have finished voting and before the voting for the current proposal is over.

**Comment by sulliwane** [comment]
fixed
