### ISSUE TITLE
New voting plan reminder

### ISSUE THREAD

**Issue by mcarlo-mzc** [mcdexio/gov-fe#8]
When creating a new voting plan, if the number of mcbs of the user does not reach the limit of the new plan, it is recommended to give a prompt to prevent the user from constantly clicking and unresponsive behavior.

**Comment by sulliwane** [comment]
fixed in https://github.com/mcdexio/gov-fe/commit/0d3985e9940f5e32fa0bcf3eef949d36990bca5d
